//! Evidence-labelled vftable metadata and raw slot access.
//! Slot calls remain the consumer's responsibility until a signature is unique.

use core::ffi::c_void;

#[derive(Clone, Copy, Debug)]
pub struct VTableInfo { pub name: &'static str, pub rva: u32, pub first_slot: usize, pub slot_count: usize, pub confidence: &'static str }

#[derive(Clone, Copy, Debug)]
pub struct VTableSlot { pub table_rva: u32, pub slot: u32, pub byte_offset: u32, pub target_rva: u32, pub target_id: Option<&'static str>, pub target_name: Option<&'static str>, pub ambiguous: bool, pub this_adjustment: Option<i32> }

pub static VTABLES: &[VTableInfo] = &[
    VTableInfo { name: "const ATL::CComObject<class CPhotoThumbnailProvider>::`vftable'{for `IInitializeWithFile'}", rva: 0x62890, first_slot: 0, slot_count: 4, confidence: "likely" },
    VTableInfo { name: "const ATL::CComObject<class CPhotoThumbnailProvider>::`vftable'{for `IInitializeWithStream'}", rva: 0x628B0, first_slot: 4, slot_count: 5, confidence: "likely" },
    VTableInfo { name: "const ATL::CComObject<class CPhotoThumbnailProvider>::`vftable'{for `IThumbnailProvider'}", rva: 0x628D8, first_slot: 9, slot_count: 4, confidence: "likely" },
    VTableInfo { name: "const ATL::CComObject<class CPolicyComponent>::`vftable'", rva: 0x628F8, first_slot: 13, slot_count: 10, confidence: "likely" },
    VTableInfo { name: "const ATL::CComObject<class CPhotoPropertyStore>::`vftable'{for `IPropertyStore'}", rva: 0x62948, first_slot: 23, slot_count: 8, confidence: "likely" },
    VTableInfo { name: "const ATL::CComObject<class CPhotoPropertyStore>::`vftable'{for `IInitializeWithStream'}", rva: 0x62988, first_slot: 31, slot_count: 5, confidence: "likely" },
    VTableInfo { name: "const ATL::CComObject<class CPhotoPropertyStore>::`vftable'{for `IInitializeWithFile'}", rva: 0x629B0, first_slot: 36, slot_count: 4, confidence: "likely" },
    VTableInfo { name: "const ATL::CComObject<class CPhotoPropertyStore>::`vftable'{for `IPropertyStoreCapabilities'}", rva: 0x629D0, first_slot: 40, slot_count: 4, confidence: "likely" },
    VTableInfo { name: "const ATL::CComObjectCached<class ATL::CComClassFactory>::`vftable'", rva: 0x65B40, first_slot: 44, slot_count: 5, confidence: "likely" },
    VTableInfo { name: "const CReadResult::`vftable'", rva: 0x65B68, first_slot: 49, slot_count: 1, confidence: "likely" },
    VTableInfo { name: "const CStringRuleReader::`vftable'", rva: 0x65BA0, first_slot: 50, slot_count: 11, confidence: "likely" },
    VTableInfo { name: "const CRationalRuleReader::`vftable'", rva: 0x65BF8, first_slot: 61, slot_count: 11, confidence: "likely" },
    VTableInfo { name: "const CIntegerRuleReader::`vftable'", rva: 0x65C50, first_slot: 72, slot_count: 11, confidence: "likely" },
    VTableInfo { name: "const CDateRuleReader::`vftable'", rva: 0x65CA8, first_slot: 83, slot_count: 11, confidence: "likely" },
    VTableInfo { name: "const CMergeStringRuleReader::`vftable'", rva: 0x65D00, first_slot: 94, slot_count: 11, confidence: "likely" },
    VTableInfo { name: "const CBinaryRuleReader::`vftable'", rva: 0x65D58, first_slot: 105, slot_count: 11, confidence: "likely" },
    VTableInfo { name: "const CBooleanRuleReader::`vftable'", rva: 0x65DB0, first_slot: 116, slot_count: 11, confidence: "likely" },
    VTableInfo { name: "const CRuleHandler::`vftable'", rva: 0x65EB8, first_slot: 127, slot_count: 2, confidence: "likely" },
    VTableInfo { name: "const ATL::CComClassFactory::`vftable'", rva: 0x65FF0, first_slot: 129, slot_count: 5, confidence: "likely" },
    VTableInfo { name: "const ATL::CComModule::`vftable'", rva: 0x66018, first_slot: 134, slot_count: 10, confidence: "likely" },
    VTableInfo { name: "const ATL::CAtlStringMgr::`vftable'", rva: 0x66068, first_slot: 144, slot_count: 6, confidence: "likely" },
    VTableInfo { name: "const CCoDynamicArray<unsigned short const *>::`vftable'", rva: 0x66098, first_slot: 150, slot_count: 1, confidence: "likely" },
    VTableInfo { name: "const CMergeStringReadResult::`vftable'", rva: 0x660A0, first_slot: 151, slot_count: 1, confidence: "likely" },
    VTableInfo { name: "const ATL::CWin32Heap::`vftable'", rva: 0x660A8, first_slot: 152, slot_count: 5, confidence: "likely" },
    VTableInfo { name: "const ATL::CComObject<class CPhotoExtractImage>::`vftable'{for `IInitializeWithStream'}", rva: 0x660D0, first_slot: 157, slot_count: 4, confidence: "likely" },
    VTableInfo { name: "const ATL::CComObject<class CPhotoExtractImage>::`vftable'{for `IInitializeWithFile'}", rva: 0x660F0, first_slot: 161, slot_count: 4, confidence: "likely" },
    VTableInfo { name: "const ATL::CComObject<class CPhotoExtractImage>::`vftable'{for `IPersistFile'}", rva: 0x66110, first_slot: 165, slot_count: 9, confidence: "likely" },
    VTableInfo { name: "const ATL::CComObject<class CPhotoExtractImage>::`vftable'{for `IExtractImage'}", rva: 0x66158, first_slot: 174, slot_count: 6, confidence: "likely" },
    VTableInfo { name: "const type_info::`vftable'", rva: 0x66220, first_slot: 180, slot_count: 1, confidence: "likely" },
    VTableInfo { name: "const ATL::CComObject<class CImageTranscode>::`vftable'", rva: 0x66278, first_slot: 181, slot_count: 5, confidence: "likely" },
    VTableInfo { name: "const ATL::CRegObject::`vftable'", rva: 0x662A0, first_slot: 186, slot_count: 6, confidence: "likely" },
    VTableInfo { name: "const CBooleanRuleWriter::`vftable'", rva: 0x662D0, first_slot: 192, slot_count: 11, confidence: "likely" },
    VTableInfo { name: "const CBinaryRuleWriter::`vftable'", rva: 0x66328, first_slot: 203, slot_count: 11, confidence: "likely" },
    VTableInfo { name: "const CIntegerRuleWriter::`vftable'", rva: 0x66380, first_slot: 214, slot_count: 11, confidence: "likely" },
    VTableInfo { name: "const CRationalRuleWriter::`vftable'", rva: 0x663D8, first_slot: 225, slot_count: 11, confidence: "likely" },
    VTableInfo { name: "const CMergeStringRuleWriter::`vftable'", rva: 0x66430, first_slot: 236, slot_count: 11, confidence: "likely" },
    VTableInfo { name: "const CStringRuleWriter::`vftable'", rva: 0x66488, first_slot: 247, slot_count: 11, confidence: "likely" },
    VTableInfo { name: "const CDateRuleWriter::`vftable'", rva: 0x664E0, first_slot: 258, slot_count: 11, confidence: "likely" },
    VTableInfo { name: "const ATL::CComObject<class DIS11::DIS11Keywords>::`vftable'", rva: 0x66538, first_slot: 269, slot_count: 15, confidence: "likely" },
    VTableInfo { name: "const wistd::__function::__base<bool __cdecl (void *, uint64_t, void *, uint64_t, unsigned int)>::`vftable'", rva: 0x665B0, first_slot: 284, slot_count: 5, confidence: "likely" },
    VTableInfo { name: "const wistd::__function::__func<class <lambda_8db0ce862824541f40dfb767113f1e28>, bool __cdecl (void *, uint64_t, class <lambda_8db0ce862824541f40dfb767113f1e28>, void *, unsigned int)>::`vftable'", rva: 0x665D8, first_slot: 289, slot_count: 5, confidence: "likely" },
    VTableInfo { name: "const ATL::CComObject<class DIS11::ErrHandler>::`vftable'", rva: 0x66600, first_slot: 294, slot_count: 7, confidence: "likely" },
    VTableInfo { name: "const DIS11::ErrHandler::`vftable'", rva: 0x66638, first_slot: 301, slot_count: 7, confidence: "likely" },
    VTableInfo { name: "const DIS11::DIS11Keywords::`vftable'", rva: 0x66670, first_slot: 308, slot_count: 15, confidence: "likely" },
    VTableInfo { name: "const wil::ResultException::`vftable'", rva: 0x666E8, first_slot: 323, slot_count: 2, confidence: "likely" },
    VTableInfo { name: "const std::exception::`vftable'", rva: 0x666F8, first_slot: 325, slot_count: 2, confidence: "likely" },
];

pub static VTABLE_SLOTS: &[VTableSlot] = &[
    VTableSlot { table_rva: 0x62890, slot: 0, byte_offset: 0, target_rva: 0x15450, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x62890, slot: 1, byte_offset: 8, target_rva: 0x13DA0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x62890, slot: 2, byte_offset: 16, target_rva: 0x16030, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x62890, slot: 3, byte_offset: 24, target_rva: 0x103B0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x628B0, slot: 0, byte_offset: 0, target_rva: 0xCF20, target_id: Some("?QueryInterface@?$CComObject@VCPhotoThumbnailProvider@@@ATL@@UEAAJAEBU_GUID@@PEAPEAX@Z"), target_name: Some("public: virtual long __cdecl ATL::CComObject<class CPhotoThumbnailProvider>::QueryInterface(struct _GUID const &, void * *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x628B0, slot: 1, byte_offset: 8, target_rva: 0x10070, target_id: Some("?AddRef@?$CComObject@VCPhotoThumbnailProvider@@@ATL@@UEAAKXZ"), target_name: Some("public: virtual unsigned long __cdecl ATL::CComObject<class CPhotoThumbnailProvider>::AddRef(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x628B0, slot: 2, byte_offset: 16, target_rva: 0xECD0, target_id: Some("?Release@?$CComObject@VCPhotoThumbnailProvider@@@ATL@@UEAAKXZ"), target_name: Some("public: virtual unsigned long __cdecl ATL::CComObject<class CPhotoThumbnailProvider>::Release(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x628B0, slot: 3, byte_offset: 24, target_rva: 0x5FF0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x628B0, slot: 4, byte_offset: 32, target_rva: 0xFE10, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x628D8, slot: 0, byte_offset: 0, target_rva: 0x15460, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x628D8, slot: 1, byte_offset: 8, target_rva: 0x13DB0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x628D8, slot: 2, byte_offset: 16, target_rva: 0x16040, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x628D8, slot: 3, byte_offset: 24, target_rva: 0x11010, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x628F8, slot: 0, byte_offset: 0, target_rva: 0x9020, target_id: Some("?QueryInterface@?$CComObject@VCPolicyComponent@@@ATL@@UEAAJAEBU_GUID@@PEAPEAX@Z"), target_name: Some("public: virtual long __cdecl ATL::CComObject<class CPolicyComponent>::QueryInterface(struct _GUID const &, void * *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x628F8, slot: 1, byte_offset: 8, target_rva: 0xEA00, target_id: Some("?AddRef@?$CComObject@VCPolicyComponent@@@ATL@@UEAAKXZ"), target_name: Some("public: virtual unsigned long __cdecl ATL::CComObject<class CPolicyComponent>::AddRef(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x628F8, slot: 2, byte_offset: 16, target_rva: 0xCC60, target_id: Some("?Release@?$CComObject@VCPolicyComponent@@@ATL@@UEAAKXZ"), target_name: Some("public: virtual unsigned long __cdecl ATL::CComObject<class CPolicyComponent>::Release(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x628F8, slot: 3, byte_offset: 24, target_rva: 0x10B70, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x628F8, slot: 4, byte_offset: 32, target_rva: 0x1910, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x628F8, slot: 5, byte_offset: 40, target_rva: 0x197A0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x628F8, slot: 6, byte_offset: 48, target_rva: 0x1670, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x628F8, slot: 7, byte_offset: 56, target_rva: 0x8C50, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x628F8, slot: 8, byte_offset: 64, target_rva: 0x10910, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x628F8, slot: 9, byte_offset: 72, target_rva: 0xCEA0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x62948, slot: 0, byte_offset: 0, target_rva: 0x15430, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x62948, slot: 1, byte_offset: 8, target_rva: 0x13320, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x62948, slot: 2, byte_offset: 16, target_rva: 0x16010, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x62948, slot: 3, byte_offset: 24, target_rva: 0x2740, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x62948, slot: 4, byte_offset: 32, target_rva: 0x2F50, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x62948, slot: 5, byte_offset: 40, target_rva: 0x28F0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x62948, slot: 6, byte_offset: 48, target_rva: 0x19510, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x62948, slot: 7, byte_offset: 56, target_rva: 0x19230, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x62988, slot: 0, byte_offset: 0, target_rva: 0x9180, target_id: Some("?QueryInterface@?$CComObject@VCPhotoPropertyStore@@@ATL@@UEAAJAEBU_GUID@@PEAPEAX@Z"), target_name: Some("public: virtual long __cdecl ATL::CComObject<class CPhotoPropertyStore>::QueryInterface(struct _GUID const &, void * *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x62988, slot: 1, byte_offset: 8, target_rva: 0xFFC0, target_id: Some("?AddRef@?$CComObject@VCPhotoPropertyStore@@@ATL@@UEAAKXZ"), target_name: Some("public: virtual unsigned long __cdecl ATL::CComObject<class CPhotoPropertyStore>::AddRef(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x62988, slot: 2, byte_offset: 16, target_rva: 0xD520, target_id: Some("?Release@?$CComObject@VCPhotoPropertyStore@@@ATL@@UEAAKXZ"), target_name: Some("public: virtual unsigned long __cdecl ATL::CComObject<class CPhotoPropertyStore>::Release(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x62988, slot: 3, byte_offset: 24, target_rva: 0x5010, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x62988, slot: 4, byte_offset: 32, target_rva: 0xE960, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x629B0, slot: 0, byte_offset: 0, target_rva: 0x15420, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x629B0, slot: 1, byte_offset: 8, target_rva: 0x13310, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x629B0, slot: 2, byte_offset: 16, target_rva: 0x16000, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x629B0, slot: 3, byte_offset: 24, target_rva: 0x19300, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x629D0, slot: 0, byte_offset: 0, target_rva: 0x15440, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x629D0, slot: 1, byte_offset: 8, target_rva: 0x13330, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x629D0, slot: 2, byte_offset: 16, target_rva: 0x16020, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x629D0, slot: 3, byte_offset: 24, target_rva: 0x193F0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65B40, slot: 0, byte_offset: 0, target_rva: 0x8AF0, target_id: Some("?QueryInterface@?$CComObjectCached@VCComClassFactory@ATL@@@ATL@@UEAAJAEBU_GUID@@PEAPEAX@Z"), target_name: Some("public: virtual long __cdecl ATL::CComObjectCached<class ATL::CComClassFactory>::QueryInterface(struct _GUID const &, void * *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x65B40, slot: 1, byte_offset: 8, target_rva: 0xCD50, target_id: Some("?AddRef@?$CComObjectCached@VCComClassFactory@ATL@@@ATL@@UEAAKXZ"), target_name: Some("public: virtual unsigned long __cdecl ATL::CComObjectCached<class ATL::CComClassFactory>::AddRef(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x65B40, slot: 2, byte_offset: 16, target_rva: 0xCE10, target_id: Some("?Release@?$CComObjectCached@VCComClassFactory@ATL@@@ATL@@UEAAKXZ"), target_name: Some("public: virtual unsigned long __cdecl ATL::CComObjectCached<class ATL::CComClassFactory>::Release(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x65B40, slot: 3, byte_offset: 24, target_rva: 0xCCF0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65B40, slot: 4, byte_offset: 32, target_rva: 0x13490, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65B68, slot: 0, byte_offset: 0, target_rva: 0xDCD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65BA0, slot: 0, byte_offset: 0, target_rva: 0xC350, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65BA0, slot: 1, byte_offset: 8, target_rva: 0xCCD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65BA0, slot: 2, byte_offset: 16, target_rva: 0x8F90, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65BA0, slot: 3, byte_offset: 24, target_rva: 0x8300, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65BA0, slot: 4, byte_offset: 32, target_rva: 0x1AFD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65BA0, slot: 5, byte_offset: 40, target_rva: 0x9470, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65BA0, slot: 6, byte_offset: 48, target_rva: 0x8450, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65BA0, slot: 7, byte_offset: 56, target_rva: 0x8920, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65BA0, slot: 8, byte_offset: 64, target_rva: 0x8640, target_id: Some("?ReadAndConvertQuery@CStringRuleReader@@UEAAJPEBGW4DiskFormats@@W4DataFormats@@PEAUtagPROPVARIANT@@@Z"), target_name: Some("public: virtual long __cdecl CStringRuleReader::ReadAndConvertQuery(unsigned short const *, enum DiskFormats, enum DataFormats, struct tagPROPVARIANT *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x65BA0, slot: 9, byte_offset: 72, target_rva: 0xA1C0, target_id: Some("?ConvertDataFormatOnRead@CStringRuleReader@@UEAAJW4DataFormats@@PEAUtagPROPVARIANT@@@Z"), target_name: Some("public: virtual long __cdecl CStringRuleReader::ConvertDataFormatOnRead(enum DataFormats, struct tagPROPVARIANT *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x65BA0, slot: 10, byte_offset: 80, target_rva: 0x6A10, target_id: Some("?ConvertDiskFormatOnRead@CStringRuleReader@@UEAAJW4DiskFormats@@PEAUtagPROPVARIANT@@@Z"), target_name: Some("public: virtual long __cdecl CStringRuleReader::ConvertDiskFormatOnRead(enum DiskFormats, struct tagPROPVARIANT *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x65BF8, slot: 0, byte_offset: 0, target_rva: 0xC350, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65BF8, slot: 1, byte_offset: 8, target_rva: 0xCCD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65BF8, slot: 2, byte_offset: 16, target_rva: 0x8F90, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65BF8, slot: 3, byte_offset: 24, target_rva: 0x8300, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65BF8, slot: 4, byte_offset: 32, target_rva: 0x1AFD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65BF8, slot: 5, byte_offset: 40, target_rva: 0x9470, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65BF8, slot: 6, byte_offset: 48, target_rva: 0x8450, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65BF8, slot: 7, byte_offset: 56, target_rva: 0x6660, target_id: Some("?ReadRulePath@CRationalRuleReader@@UEAAJPEBURULE_PATH_INFO@@PEAPEAVCReadResult@@@Z"), target_name: Some("public: virtual long __cdecl CRationalRuleReader::ReadRulePath(struct RULE_PATH_INFO const *, class CReadResult * *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x65BF8, slot: 8, byte_offset: 64, target_rva: 0x8A20, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65BF8, slot: 9, byte_offset: 72, target_rva: 0x10B40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65BF8, slot: 10, byte_offset: 80, target_rva: 0xA7B0, target_id: Some("?ConvertDiskFormatOnRead@CRationalRuleReader@@UEAAJW4DiskFormats@@PEAUtagPROPVARIANT@@@Z"), target_name: Some("public: virtual long __cdecl CRationalRuleReader::ConvertDiskFormatOnRead(enum DiskFormats, struct tagPROPVARIANT *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x65C50, slot: 0, byte_offset: 0, target_rva: 0xC350, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65C50, slot: 1, byte_offset: 8, target_rva: 0xCCD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65C50, slot: 2, byte_offset: 16, target_rva: 0x8F90, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65C50, slot: 3, byte_offset: 24, target_rva: 0x8300, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65C50, slot: 4, byte_offset: 32, target_rva: 0x1AFD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65C50, slot: 5, byte_offset: 40, target_rva: 0x9470, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65C50, slot: 6, byte_offset: 48, target_rva: 0x8450, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65C50, slot: 7, byte_offset: 56, target_rva: 0x8920, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65C50, slot: 8, byte_offset: 64, target_rva: 0x8A20, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65C50, slot: 9, byte_offset: 72, target_rva: 0x9760, target_id: Some("?ConvertDataFormatOnRead@CIntegerRuleReader@@UEAAJW4DataFormats@@PEAUtagPROPVARIANT@@@Z"), target_name: Some("public: virtual long __cdecl CIntegerRuleReader::ConvertDataFormatOnRead(enum DataFormats, struct tagPROPVARIANT *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x65C50, slot: 10, byte_offset: 80, target_rva: 0x6C10, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65CA8, slot: 0, byte_offset: 0, target_rva: 0xC350, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65CA8, slot: 1, byte_offset: 8, target_rva: 0xCCD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65CA8, slot: 2, byte_offset: 16, target_rva: 0x8F90, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65CA8, slot: 3, byte_offset: 24, target_rva: 0x8300, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65CA8, slot: 4, byte_offset: 32, target_rva: 0x1AFD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65CA8, slot: 5, byte_offset: 40, target_rva: 0x9470, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65CA8, slot: 6, byte_offset: 48, target_rva: 0x8450, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65CA8, slot: 7, byte_offset: 56, target_rva: 0xC3E0, target_id: Some("?ReadRulePath@CDateRuleReader@@UEAAJPEBURULE_PATH_INFO@@PEAPEAVCReadResult@@@Z"), target_name: Some("public: virtual long __cdecl CDateRuleReader::ReadRulePath(struct RULE_PATH_INFO const *, class CReadResult * *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x65CA8, slot: 8, byte_offset: 64, target_rva: 0x8A20, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65CA8, slot: 9, byte_offset: 72, target_rva: 0xF2A0, target_id: Some("?ConvertDataFormatOnRead@CDateRuleReader@@UEAAJW4DataFormats@@PEAUtagPROPVARIANT@@@Z"), target_name: Some("public: virtual long __cdecl CDateRuleReader::ConvertDataFormatOnRead(enum DataFormats, struct tagPROPVARIANT *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x65CA8, slot: 10, byte_offset: 80, target_rva: 0x6C10, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65D00, slot: 0, byte_offset: 0, target_rva: 0xC350, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65D00, slot: 1, byte_offset: 8, target_rva: 0xCCD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65D00, slot: 2, byte_offset: 16, target_rva: 0x8F90, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65D00, slot: 3, byte_offset: 24, target_rva: 0xB370, target_id: Some("?ReadKey@CMergeStringRuleReader@@UEAAJPEAUtagPROPVARIANT@@@Z"), target_name: Some("public: virtual long __cdecl CMergeStringRuleReader::ReadKey(struct tagPROPVARIANT *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x65D00, slot: 4, byte_offset: 32, target_rva: 0x198A0, target_id: Some("?SettingChecksumWouldAffectReadPath@CMergeStringRuleReader@@UEAAJPEBGPEAH@Z"), target_name: Some("public: virtual long __cdecl CMergeStringRuleReader::SettingChecksumWouldAffectReadPath(unsigned short const *, int *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x65D00, slot: 5, byte_offset: 40, target_rva: 0x9470, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65D00, slot: 6, byte_offset: 48, target_rva: 0x8450, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65D00, slot: 7, byte_offset: 56, target_rva: 0xD930, target_id: Some("?ReadRulePath@CMergeStringRuleReader@@MEAAJPEBURULE_PATH_INFO@@PEAPEAVCReadResult@@@Z"), target_name: Some("protected: virtual long __cdecl CMergeStringRuleReader::ReadRulePath(struct RULE_PATH_INFO const *, class CReadResult * *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x65D00, slot: 8, byte_offset: 64, target_rva: 0x8640, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65D00, slot: 9, byte_offset: 72, target_rva: 0xA060, target_id: Some("?ConvertDataFormatOnRead@CMergeStringRuleReader@@MEAAJW4DataFormats@@PEAUtagPROPVARIANT@@@Z"), target_name: Some("protected: virtual long __cdecl CMergeStringRuleReader::ConvertDataFormatOnRead(enum DataFormats, struct tagPROPVARIANT *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x65D00, slot: 10, byte_offset: 80, target_rva: 0x6A10, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65D58, slot: 0, byte_offset: 0, target_rva: 0xC350, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65D58, slot: 1, byte_offset: 8, target_rva: 0xCCD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65D58, slot: 2, byte_offset: 16, target_rva: 0x8F90, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65D58, slot: 3, byte_offset: 24, target_rva: 0x8300, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65D58, slot: 4, byte_offset: 32, target_rva: 0x1AFD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65D58, slot: 5, byte_offset: 40, target_rva: 0x9470, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65D58, slot: 6, byte_offset: 48, target_rva: 0x8450, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65D58, slot: 7, byte_offset: 56, target_rva: 0x8920, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65D58, slot: 8, byte_offset: 64, target_rva: 0x8A20, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65D58, slot: 9, byte_offset: 72, target_rva: 0xF840, target_id: Some("?ConvertDataFormatOnRead@CBinaryRuleReader@@UEAAJW4DataFormats@@PEAUtagPROPVARIANT@@@Z"), target_name: Some("public: virtual long __cdecl CBinaryRuleReader::ConvertDataFormatOnRead(enum DataFormats, struct tagPROPVARIANT *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x65D58, slot: 10, byte_offset: 80, target_rva: 0x6C10, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65DB0, slot: 0, byte_offset: 0, target_rva: 0xC350, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65DB0, slot: 1, byte_offset: 8, target_rva: 0xCCD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65DB0, slot: 2, byte_offset: 16, target_rva: 0x8F90, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65DB0, slot: 3, byte_offset: 24, target_rva: 0x8300, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65DB0, slot: 4, byte_offset: 32, target_rva: 0x1AFD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65DB0, slot: 5, byte_offset: 40, target_rva: 0x9470, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65DB0, slot: 6, byte_offset: 48, target_rva: 0x8450, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65DB0, slot: 7, byte_offset: 56, target_rva: 0x8920, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65DB0, slot: 8, byte_offset: 64, target_rva: 0x8A20, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65DB0, slot: 9, byte_offset: 72, target_rva: 0x10B40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65DB0, slot: 10, byte_offset: 80, target_rva: 0x13820, target_id: Some("?ConvertDiskFormatOnRead@CBooleanRuleReader@@UEAAJW4DiskFormats@@PEAUtagPROPVARIANT@@@Z"), target_name: Some("public: virtual long __cdecl CBooleanRuleReader::ConvertDiskFormatOnRead(enum DiskFormats, struct tagPROPVARIANT *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x65EB8, slot: 0, byte_offset: 0, target_rva: 0x1A590, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65EB8, slot: 1, byte_offset: 8, target_rva: 0xCCD0, target_id: Some("?Initialize@CRuleHandler@@MEAAJPEBUKEY_LIST_ENTRY@@PEBUCAPABILITIES_LIST_ENTRY@@PEBURULE_PATH_INFO@@I@Z"), target_name: Some("protected: virtual long __cdecl CRuleHandler::Initialize(struct KEY_LIST_ENTRY const *, struct CAPABILITIES_LIST_ENTRY const *, struct RULE_PATH_INFO const *, unsigned int)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x65FF0, slot: 0, byte_offset: 0, target_rva: 0x12BF0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65FF0, slot: 1, byte_offset: 8, target_rva: 0x12BF0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65FF0, slot: 2, byte_offset: 16, target_rva: 0x12BF0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x65FF0, slot: 3, byte_offset: 24, target_rva: 0xCCF0, target_id: Some("?CreateInstance@CComClassFactory@ATL@@UEAAJPEAUIUnknown@@AEBU_GUID@@PEAPEAX@Z"), target_name: Some("public: virtual long __cdecl ATL::CComClassFactory::CreateInstance(struct IUnknown *, struct _GUID const &, void * *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x65FF0, slot: 4, byte_offset: 32, target_rva: 0x13490, target_id: Some("?LockServer@CComClassFactory@ATL@@UEAAJH@Z"), target_name: Some("public: virtual long __cdecl ATL::CComClassFactory::LockServer(int)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66018, slot: 0, byte_offset: 0, target_rva: 0x13A80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66018, slot: 1, byte_offset: 8, target_rva: 0xD5A0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66018, slot: 2, byte_offset: 16, target_rva: 0xDD30, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66018, slot: 3, byte_offset: 24, target_rva: 0x11AB0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66018, slot: 4, byte_offset: 32, target_rva: 0x14ED0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66018, slot: 5, byte_offset: 40, target_rva: 0x13D70, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66018, slot: 6, byte_offset: 48, target_rva: 0x16340, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66018, slot: 7, byte_offset: 56, target_rva: 0x16340, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66018, slot: 8, byte_offset: 64, target_rva: 0x16880, target_id: Some("?UpdateRegistryFromResourceS@CComModule@ATL@@UEAAJIHPEAU_ATL_REGMAP_ENTRY@2@@Z"), target_name: Some("public: virtual long __cdecl ATL::CComModule::UpdateRegistryFromResourceS(unsigned int, int, struct ATL::_ATL_REGMAP_ENTRY *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66018, slot: 9, byte_offset: 72, target_rva: 0x16890, target_id: Some("?UpdateRegistryFromResourceS@CComModule@ATL@@UEAAJPEBGHPEAU_ATL_REGMAP_ENTRY@2@@Z"), target_name: Some("public: virtual long __cdecl ATL::CComModule::UpdateRegistryFromResourceS(unsigned short const *, int, struct ATL::_ATL_REGMAP_ENTRY *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66068, slot: 0, byte_offset: 0, target_rva: 0xF070, target_id: Some("?Allocate@CAtlStringMgr@ATL@@UEAAPEAUCStringData@2@HH@Z"), target_name: Some("public: virtual struct ATL::CStringData * __cdecl ATL::CAtlStringMgr::Allocate(int, int)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66068, slot: 1, byte_offset: 8, target_rva: 0x104A0, target_id: Some("?Free@CAtlStringMgr@ATL@@UEAAXPEAUCStringData@2@@Z"), target_name: Some("public: virtual void __cdecl ATL::CAtlStringMgr::Free(struct ATL::CStringData *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66068, slot: 2, byte_offset: 16, target_rva: 0x29220, target_id: Some("?Reallocate@CAtlStringMgr@ATL@@UEAAPEAUCStringData@2@PEAU32@HH@Z"), target_name: Some("public: virtual struct ATL::CStringData * __cdecl ATL::CAtlStringMgr::Reallocate(struct ATL::CStringData *, int, int)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66068, slot: 3, byte_offset: 24, target_rva: 0x10160, target_id: Some("?GetNilString@CAtlStringMgr@ATL@@UEAAPEAUCStringData@2@XZ"), target_name: Some("public: virtual struct ATL::CStringData * __cdecl ATL::CAtlStringMgr::GetNilString(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66068, slot: 4, byte_offset: 32, target_rva: 0x10170, target_id: Some("?Clone@CAtlStringMgr@ATL@@UEAAPEAUIAtlStringMgr@2@XZ"), target_name: Some("public: virtual struct ATL::IAtlStringMgr * __cdecl ATL::CAtlStringMgr::Clone(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66068, slot: 5, byte_offset: 40, target_rva: 0x29180, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66098, slot: 0, byte_offset: 0, target_rva: 0x20F70, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x660A0, slot: 0, byte_offset: 0, target_rva: 0x102A0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x660A8, slot: 0, byte_offset: 0, target_rva: 0x105C0, target_id: Some("?Allocate@CWin32Heap@ATL@@UEAAPEAX_K@Z"), target_name: Some("public: virtual void * __cdecl ATL::CWin32Heap::Allocate(uint64_t)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x660A8, slot: 1, byte_offset: 8, target_rva: 0xFED0, target_id: Some("?Free@CWin32Heap@ATL@@UEAAXPEAX@Z"), target_name: Some("public: virtual void __cdecl ATL::CWin32Heap::Free(void *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x660A8, slot: 2, byte_offset: 16, target_rva: 0x292A0, target_id: Some("?Reallocate@CWin32Heap@ATL@@UEAAPEAXPEAX_K@Z"), target_name: Some("public: virtual void * __cdecl ATL::CWin32Heap::Reallocate(void *, uint64_t)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x660A8, slot: 3, byte_offset: 24, target_rva: 0x29200, target_id: Some("?GetSize@CWin32Heap@ATL@@UEAA_KPEAX@Z"), target_name: Some("public: virtual uint64_t __cdecl ATL::CWin32Heap::GetSize(void *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x660A8, slot: 4, byte_offset: 32, target_rva: 0x291C0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x660D0, slot: 0, byte_offset: 0, target_rva: 0x134D0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x660D0, slot: 1, byte_offset: 8, target_rva: 0x13320, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x660D0, slot: 2, byte_offset: 16, target_rva: 0x13500, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x660D0, slot: 3, byte_offset: 24, target_rva: 0x6420, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x660F0, slot: 0, byte_offset: 0, target_rva: 0x134E0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x660F0, slot: 1, byte_offset: 8, target_rva: 0x13330, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x660F0, slot: 2, byte_offset: 16, target_rva: 0x13510, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x660F0, slot: 3, byte_offset: 24, target_rva: 0x1BD70, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66110, slot: 0, byte_offset: 0, target_rva: 0x134C0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66110, slot: 1, byte_offset: 8, target_rva: 0x13310, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66110, slot: 2, byte_offset: 16, target_rva: 0x134F0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66110, slot: 3, byte_offset: 24, target_rva: 0x1BB10, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66110, slot: 4, byte_offset: 32, target_rva: 0x1BEE0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66110, slot: 5, byte_offset: 40, target_rva: 0x1BF30, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66110, slot: 6, byte_offset: 48, target_rva: 0x1BEE0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66110, slot: 7, byte_offset: 56, target_rva: 0x1BEE0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66110, slot: 8, byte_offset: 64, target_rva: 0x1BB30, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66158, slot: 0, byte_offset: 0, target_rva: 0x10B50, target_id: Some("?QueryInterface@?$CComObject@VCPhotoExtractImage@@@ATL@@UEAAJAEBU_GUID@@PEAPEAX@Z"), target_name: Some("public: virtual long __cdecl ATL::CComObject<class CPhotoExtractImage>::QueryInterface(struct _GUID const &, void * *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66158, slot: 1, byte_offset: 8, target_rva: 0xFFC0, target_id: Some("?AddRef@?$CComObject@VCPhotoExtractImage@@@ATL@@UEAAKXZ"), target_name: Some("public: virtual unsigned long __cdecl ATL::CComObject<class CPhotoExtractImage>::AddRef(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66158, slot: 2, byte_offset: 16, target_rva: 0x10720, target_id: Some("?Release@?$CComObject@VCPhotoExtractImage@@@ATL@@UEAAKXZ"), target_name: Some("public: virtual unsigned long __cdecl ATL::CComObject<class CPhotoExtractImage>::Release(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66158, slot: 3, byte_offset: 24, target_rva: 0x1BC50, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66158, slot: 4, byte_offset: 32, target_rva: 0x1B800, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66158, slot: 5, byte_offset: 40, target_rva: 0x132D0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66220, slot: 0, byte_offset: 0, target_rva: 0x12200, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66278, slot: 0, byte_offset: 0, target_rva: 0x15400, target_id: Some("?QueryInterface@?$CComObject@VCImageTranscode@@@ATL@@UEAAJAEBU_GUID@@PEAPEAX@Z"), target_name: Some("public: virtual long __cdecl ATL::CComObject<class CImageTranscode>::QueryInterface(struct _GUID const &, void * *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66278, slot: 1, byte_offset: 8, target_rva: 0xEA00, target_id: Some("?AddRef@?$CComObject@VCImageTranscode@@@ATL@@UEAAKXZ"), target_name: Some("public: virtual unsigned long __cdecl ATL::CComObject<class CImageTranscode>::AddRef(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66278, slot: 2, byte_offset: 16, target_rva: 0x15F90, target_id: Some("?Release@?$CComObject@VCImageTranscode@@@ATL@@UEAAKXZ"), target_name: Some("public: virtual unsigned long __cdecl ATL::CComObject<class CImageTranscode>::Release(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66278, slot: 3, byte_offset: 24, target_rva: 0x1C100, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66278, slot: 4, byte_offset: 32, target_rva: 0x13A40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x662A0, slot: 0, byte_offset: 0, target_rva: 0x15470, target_id: Some("?QueryInterface@CRegObject@ATL@@UEAAJAEBU_GUID@@PEAPEAX@Z"), target_name: Some("public: virtual long __cdecl ATL::CRegObject::QueryInterface(struct _GUID const &, void * *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x662A0, slot: 1, byte_offset: 8, target_rva: 0x13DC0, target_id: Some("?AddRef@CRegObject@ATL@@UEAAKXZ"), target_name: Some("public: virtual unsigned long __cdecl ATL::CRegObject::AddRef(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x662A0, slot: 2, byte_offset: 16, target_rva: 0x10B40, target_id: Some("?Release@CRegObject@ATL@@UEAAKXZ"), target_name: Some("public: virtual unsigned long __cdecl ATL::CRegObject::Release(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x662A0, slot: 3, byte_offset: 24, target_rva: 0x13DD0, target_id: Some("?AddReplacement@CRegObject@ATL@@UEAAJPEBG0@Z"), target_name: Some("public: virtual long __cdecl ATL::CRegObject::AddReplacement(unsigned short const *, unsigned short const *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x662A0, slot: 4, byte_offset: 32, target_rva: 0x14C00, target_id: Some("?ClearReplacements@CRegObject@ATL@@UEAAJXZ"), target_name: Some("public: virtual long __cdecl ATL::CRegObject::ClearReplacements(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x662A0, slot: 5, byte_offset: 40, target_rva: 0x13AD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x662D0, slot: 0, byte_offset: 0, target_rva: 0xEBD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x662D0, slot: 1, byte_offset: 8, target_rva: 0xCCD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x662D0, slot: 2, byte_offset: 16, target_rva: 0x1AC10, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x662D0, slot: 3, byte_offset: 24, target_rva: 0x1B250, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x662D0, slot: 4, byte_offset: 32, target_rva: 0xF5E0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x662D0, slot: 5, byte_offset: 40, target_rva: 0x1A720, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x662D0, slot: 6, byte_offset: 48, target_rva: 0x1AE70, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x662D0, slot: 7, byte_offset: 56, target_rva: 0x1B440, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x662D0, slot: 8, byte_offset: 64, target_rva: 0x1A850, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x662D0, slot: 9, byte_offset: 72, target_rva: 0x19730, target_id: Some("?ConvertDataFormatOnWrite@CBooleanRuleWriter@@MEAAJW4DataFormats@@PEAUtagPROPVARIANT@@@Z"), target_name: Some("protected: virtual long __cdecl CBooleanRuleWriter::ConvertDataFormatOnWrite(enum DataFormats, struct tagPROPVARIANT *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x662D0, slot: 10, byte_offset: 80, target_rva: 0x1A940, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66328, slot: 0, byte_offset: 0, target_rva: 0xEBD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66328, slot: 1, byte_offset: 8, target_rva: 0xCCD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66328, slot: 2, byte_offset: 16, target_rva: 0x1AC10, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66328, slot: 3, byte_offset: 24, target_rva: 0x1B250, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66328, slot: 4, byte_offset: 32, target_rva: 0xF5E0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66328, slot: 5, byte_offset: 40, target_rva: 0x1A720, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66328, slot: 6, byte_offset: 48, target_rva: 0x1AE70, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66328, slot: 7, byte_offset: 56, target_rva: 0x1B440, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66328, slot: 8, byte_offset: 64, target_rva: 0x1A850, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66328, slot: 9, byte_offset: 72, target_rva: 0x13580, target_id: Some("?ConvertDataFormatOnWrite@CBinaryRuleWriter@@MEAAJW4DataFormats@@PEAUtagPROPVARIANT@@@Z"), target_name: Some("protected: virtual long __cdecl CBinaryRuleWriter::ConvertDataFormatOnWrite(enum DataFormats, struct tagPROPVARIANT *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66328, slot: 10, byte_offset: 80, target_rva: 0x1A9D0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66380, slot: 0, byte_offset: 0, target_rva: 0xEBD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66380, slot: 1, byte_offset: 8, target_rva: 0xCCD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66380, slot: 2, byte_offset: 16, target_rva: 0x1AC10, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66380, slot: 3, byte_offset: 24, target_rva: 0x1B250, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66380, slot: 4, byte_offset: 32, target_rva: 0xF5E0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66380, slot: 5, byte_offset: 40, target_rva: 0x1A720, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66380, slot: 6, byte_offset: 48, target_rva: 0x1AE70, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66380, slot: 7, byte_offset: 56, target_rva: 0x1B440, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66380, slot: 8, byte_offset: 64, target_rva: 0x16B90, target_id: Some("?ConvertAndWriteQuery@CIntegerRuleWriter@@MEAAJPEBGW4DiskFormats@@W4DataFormats@@PEBUtagPROPVARIANT@@@Z"), target_name: Some("protected: virtual long __cdecl CIntegerRuleWriter::ConvertAndWriteQuery(unsigned short const *, enum DiskFormats, enum DataFormats, struct tagPROPVARIANT const *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66380, slot: 9, byte_offset: 72, target_rva: 0x19760, target_id: Some("?ConvertDataFormatOnWrite@CIntegerRuleWriter@@MEAAJW4DataFormats@@PEAUtagPROPVARIANT@@@Z"), target_name: Some("protected: virtual long __cdecl CIntegerRuleWriter::ConvertDataFormatOnWrite(enum DataFormats, struct tagPROPVARIANT *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66380, slot: 10, byte_offset: 80, target_rva: 0x1A940, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x663D8, slot: 0, byte_offset: 0, target_rva: 0xEBD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x663D8, slot: 1, byte_offset: 8, target_rva: 0xCCD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x663D8, slot: 2, byte_offset: 16, target_rva: 0x1AC10, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x663D8, slot: 3, byte_offset: 24, target_rva: 0x1B250, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x663D8, slot: 4, byte_offset: 32, target_rva: 0xF5E0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x663D8, slot: 5, byte_offset: 40, target_rva: 0x1A720, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x663D8, slot: 6, byte_offset: 48, target_rva: 0x1AE70, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x663D8, slot: 7, byte_offset: 56, target_rva: 0x19EB0, target_id: Some("?WriteRulePath@CRationalRuleWriter@@MEAAJPEBURULE_PATH_INFO@@PEBUtagPROPVARIANT@@@Z"), target_name: Some("protected: virtual long __cdecl CRationalRuleWriter::WriteRulePath(struct RULE_PATH_INFO const *, struct tagPROPVARIANT const *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x663D8, slot: 8, byte_offset: 64, target_rva: 0x1A850, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x663D8, slot: 9, byte_offset: 72, target_rva: 0x10B40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x663D8, slot: 10, byte_offset: 80, target_rva: 0x19B00, target_id: Some("?ConvertDiskFormatOnWrite@CRationalRuleWriter@@MEAAJW4DiskFormats@@PEAUtagPROPVARIANT@@@Z"), target_name: Some("protected: virtual long __cdecl CRationalRuleWriter::ConvertDiskFormatOnWrite(enum DiskFormats, struct tagPROPVARIANT *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66430, slot: 0, byte_offset: 0, target_rva: 0xEBD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66430, slot: 1, byte_offset: 8, target_rva: 0xCCD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66430, slot: 2, byte_offset: 16, target_rva: 0x1AC10, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66430, slot: 3, byte_offset: 24, target_rva: 0x1B250, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66430, slot: 4, byte_offset: 32, target_rva: 0xF5E0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66430, slot: 5, byte_offset: 40, target_rva: 0x20CA0, target_id: Some("?CheckPathAllowed@CMergeStringRuleWriter@@MEAAJPEBURULE_PATH_INFO@@PEBUtagPROPVARIANT@@PEAW4Enum@PathAllowedType@@@Z"), target_name: Some("protected: virtual long __cdecl CMergeStringRuleWriter::CheckPathAllowed(struct RULE_PATH_INFO const *, struct tagPROPVARIANT const *, enum PathAllowedType::Enum *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66430, slot: 6, byte_offset: 48, target_rva: 0x1AE70, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66430, slot: 7, byte_offset: 56, target_rva: 0x1B440, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66430, slot: 8, byte_offset: 64, target_rva: 0x18FC0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66430, slot: 9, byte_offset: 72, target_rva: 0x20D70, target_id: Some("?ConvertDataFormatOnWrite@CMergeStringRuleWriter@@MEAAJW4DataFormats@@PEAUtagPROPVARIANT@@@Z"), target_name: Some("protected: virtual long __cdecl CMergeStringRuleWriter::ConvertDataFormatOnWrite(enum DataFormats, struct tagPROPVARIANT *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66430, slot: 10, byte_offset: 80, target_rva: 0x19130, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66488, slot: 0, byte_offset: 0, target_rva: 0xEBD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66488, slot: 1, byte_offset: 8, target_rva: 0xCCD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66488, slot: 2, byte_offset: 16, target_rva: 0x1AC10, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66488, slot: 3, byte_offset: 24, target_rva: 0x1B250, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66488, slot: 4, byte_offset: 32, target_rva: 0xF5E0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66488, slot: 5, byte_offset: 40, target_rva: 0x1A720, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66488, slot: 6, byte_offset: 48, target_rva: 0x1AE70, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66488, slot: 7, byte_offset: 56, target_rva: 0x1B440, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66488, slot: 8, byte_offset: 64, target_rva: 0x18FC0, target_id: Some("?ConvertAndWriteQuery@CStringRuleWriter@@MEAAJPEBGW4DiskFormats@@W4DataFormats@@PEBUtagPROPVARIANT@@@Z"), target_name: Some("protected: virtual long __cdecl CStringRuleWriter::ConvertAndWriteQuery(unsigned short const *, enum DiskFormats, enum DataFormats, struct tagPROPVARIANT const *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66488, slot: 9, byte_offset: 72, target_rva: 0x19070, target_id: Some("?ConvertDataFormatOnWrite@CStringRuleWriter@@MEAAJW4DataFormats@@PEAUtagPROPVARIANT@@@Z"), target_name: Some("protected: virtual long __cdecl CStringRuleWriter::ConvertDataFormatOnWrite(enum DataFormats, struct tagPROPVARIANT *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66488, slot: 10, byte_offset: 80, target_rva: 0x19130, target_id: Some("?ConvertDiskFormatOnWrite@CStringRuleWriter@@MEAAJW4DiskFormats@@PEAUtagPROPVARIANT@@@Z"), target_name: Some("protected: virtual long __cdecl CStringRuleWriter::ConvertDiskFormatOnWrite(enum DiskFormats, struct tagPROPVARIANT *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x664E0, slot: 0, byte_offset: 0, target_rva: 0xEBD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x664E0, slot: 1, byte_offset: 8, target_rva: 0xCCD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x664E0, slot: 2, byte_offset: 16, target_rva: 0x1AC10, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x664E0, slot: 3, byte_offset: 24, target_rva: 0x1B250, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x664E0, slot: 4, byte_offset: 32, target_rva: 0xF5E0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x664E0, slot: 5, byte_offset: 40, target_rva: 0x1A720, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x664E0, slot: 6, byte_offset: 48, target_rva: 0x1AE70, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x664E0, slot: 7, byte_offset: 56, target_rva: 0x1A350, target_id: Some("?WriteRulePath@CDateRuleWriter@@MEAAJPEBURULE_PATH_INFO@@PEBUtagPROPVARIANT@@@Z"), target_name: Some("protected: virtual long __cdecl CDateRuleWriter::WriteRulePath(struct RULE_PATH_INFO const *, struct tagPROPVARIANT const *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x664E0, slot: 8, byte_offset: 64, target_rva: 0x1A850, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x664E0, slot: 9, byte_offset: 72, target_rva: 0x1A250, target_id: Some("?ConvertDataFormatOnWrite@CDateRuleWriter@@MEAAJW4DataFormats@@PEAUtagPROPVARIANT@@@Z"), target_name: Some("protected: virtual long __cdecl CDateRuleWriter::ConvertDataFormatOnWrite(enum DataFormats, struct tagPROPVARIANT *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x664E0, slot: 10, byte_offset: 80, target_rva: 0x1A9D0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66538, slot: 0, byte_offset: 0, target_rva: 0x1FB70, target_id: Some("?QueryInterface@?$CComObject@VDIS11Keywords@DIS11@@@ATL@@UEAAJAEBU_GUID@@PEAPEAX@Z"), target_name: Some("public: virtual long __cdecl ATL::CComObject<class DIS11::DIS11Keywords>::QueryInterface(struct _GUID const &, void * *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66538, slot: 1, byte_offset: 8, target_rva: 0xEA00, target_id: Some("?AddRef@?$CComObject@VDIS11Keywords@DIS11@@@ATL@@UEAAKXZ"), target_name: Some("public: virtual unsigned long __cdecl ATL::CComObject<class DIS11::DIS11Keywords>::AddRef(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66538, slot: 2, byte_offset: 16, target_rva: 0x1FCB0, target_id: Some("?Release@?$CComObject@VDIS11Keywords@DIS11@@@ATL@@UEAAKXZ"), target_name: Some("public: virtual unsigned long __cdecl ATL::CComObject<class DIS11::DIS11Keywords>::Release(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66538, slot: 3, byte_offset: 24, target_rva: 0x10B40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66538, slot: 4, byte_offset: 32, target_rva: 0x10B40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66538, slot: 5, byte_offset: 40, target_rva: 0x10B40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66538, slot: 6, byte_offset: 48, target_rva: 0x10B40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66538, slot: 7, byte_offset: 56, target_rva: 0x10B40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66538, slot: 8, byte_offset: 64, target_rva: 0x28320, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66538, slot: 9, byte_offset: 72, target_rva: 0x27F70, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66538, slot: 10, byte_offset: 80, target_rva: 0x10B40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66538, slot: 11, byte_offset: 88, target_rva: 0x10B40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66538, slot: 12, byte_offset: 96, target_rva: 0x10B40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66538, slot: 13, byte_offset: 104, target_rva: 0x10B40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66538, slot: 14, byte_offset: 112, target_rva: 0x1CF40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x665B0, slot: 0, byte_offset: 0, target_rva: 0x222E0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x665B0, slot: 1, byte_offset: 8, target_rva: 0x12BF0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x665B0, slot: 2, byte_offset: 16, target_rva: 0x12BF0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x665B0, slot: 3, byte_offset: 24, target_rva: 0x12BF0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x665B0, slot: 4, byte_offset: 32, target_rva: 0x12BF0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x665D8, slot: 0, byte_offset: 0, target_rva: 0x22320, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x665D8, slot: 1, byte_offset: 8, target_rva: 0x27DE0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x665D8, slot: 2, byte_offset: 16, target_rva: 0x27DE0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x665D8, slot: 3, byte_offset: 24, target_rva: 0x10490, target_id: Some("?destroy@?$__func@V<lambda_8db0ce862824541f40dfb767113f1e28>@@$$A6A_NPEAX_K01I@Z@__function@wistd@@UEAAXXZ"), target_name: Some("public: virtual void __cdecl wistd::__function::__func<class <lambda_8db0ce862824541f40dfb767113f1e28>, bool __cdecl (void *, uint64_t, class <lambda_8db0ce862824541f40dfb767113f1e28>, void *, unsigned int)>::destroy(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x665D8, slot: 4, byte_offset: 32, target_rva: 0x22230, target_id: Some("??R?$__func@V<lambda_8db0ce862824541f40dfb767113f1e28>@@$$A6A_NPEAX_K01I@Z@__function@wistd@@UEAA_N$$QEAPEAX$$QEA_K01$$QEAI@Z"), target_name: Some("public: virtual bool __cdecl wistd::__function::__func<class <lambda_8db0ce862824541f40dfb767113f1e28>, bool __cdecl (void *, uint64_t, class <lambda_8db0ce862824541f40dfb767113f1e28>, void *, unsigned int)>::operator()(void * &&, uint64_t &&, void * &&, uint64_t &&, unsigned int &&)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66600, slot: 0, byte_offset: 0, target_rva: 0x25500, target_id: Some("?QueryInterface@?$CComObject@VErrHandler@DIS11@@@ATL@@UEAAJAEBU_GUID@@PEAPEAX@Z"), target_name: Some("public: virtual long __cdecl ATL::CComObject<class DIS11::ErrHandler>::QueryInterface(struct _GUID const &, void * *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66600, slot: 1, byte_offset: 8, target_rva: 0xEA00, target_id: Some("?AddRef@?$CComObject@VErrHandler@DIS11@@@ATL@@UEAAKXZ"), target_name: Some("public: virtual unsigned long __cdecl ATL::CComObject<class DIS11::ErrHandler>::AddRef(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66600, slot: 2, byte_offset: 16, target_rva: 0x260F0, target_id: Some("?Release@?$CComObject@VErrHandler@DIS11@@@ATL@@UEAAKXZ"), target_name: Some("public: virtual unsigned long __cdecl ATL::CComObject<class DIS11::ErrHandler>::Release(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66600, slot: 3, byte_offset: 24, target_rva: 0x10B40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66600, slot: 4, byte_offset: 32, target_rva: 0x28060, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66600, slot: 5, byte_offset: 40, target_rva: 0x10B40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66600, slot: 6, byte_offset: 48, target_rva: 0x222A0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66638, slot: 0, byte_offset: 0, target_rva: 0x12BF0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66638, slot: 1, byte_offset: 8, target_rva: 0x12BF0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66638, slot: 2, byte_offset: 16, target_rva: 0x12BF0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66638, slot: 3, byte_offset: 24, target_rva: 0x10B40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66638, slot: 4, byte_offset: 32, target_rva: 0x28060, target_id: Some("?fatalError@ErrHandler@DIS11@@UEAAJPEAUISAXLocator@@PEBGJ@Z"), target_name: Some("public: virtual long __cdecl DIS11::ErrHandler::fatalError(struct ISAXLocator *, unsigned short const *, long)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66638, slot: 5, byte_offset: 40, target_rva: 0x10B40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66638, slot: 6, byte_offset: 48, target_rva: 0x223A0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66670, slot: 0, byte_offset: 0, target_rva: 0x12BF0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66670, slot: 1, byte_offset: 8, target_rva: 0x12BF0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66670, slot: 2, byte_offset: 16, target_rva: 0x12BF0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66670, slot: 3, byte_offset: 24, target_rva: 0x10B40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66670, slot: 4, byte_offset: 32, target_rva: 0x10B40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66670, slot: 5, byte_offset: 40, target_rva: 0x10B40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66670, slot: 6, byte_offset: 48, target_rva: 0x10B40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66670, slot: 7, byte_offset: 56, target_rva: 0x10B40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66670, slot: 8, byte_offset: 64, target_rva: 0x28320, target_id: Some("?startElement@DIS11Keywords@DIS11@@UEAAJPEBGH0H0HPEAUISAXAttributes@@@Z"), target_name: Some("public: virtual long __cdecl DIS11::DIS11Keywords::startElement(unsigned short const *, int, unsigned short const *, int, unsigned short const *, int, struct ISAXAttributes *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66670, slot: 9, byte_offset: 72, target_rva: 0x27F70, target_id: Some("?endElement@DIS11Keywords@DIS11@@UEAAJPEBGH0H0H@Z"), target_name: Some("public: virtual long __cdecl DIS11::DIS11Keywords::endElement(unsigned short const *, int, unsigned short const *, int, unsigned short const *, int)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x66670, slot: 10, byte_offset: 80, target_rva: 0x10B40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66670, slot: 11, byte_offset: 88, target_rva: 0x10B40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66670, slot: 12, byte_offset: 96, target_rva: 0x10B40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66670, slot: 13, byte_offset: 104, target_rva: 0x10B40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x66670, slot: 14, byte_offset: 112, target_rva: 0x22360, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x666E8, slot: 0, byte_offset: 0, target_rva: 0x223F0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x666E8, slot: 1, byte_offset: 8, target_rva: 0x283F0, target_id: Some("?what@ResultException@wil@@UEBAPEBDXZ"), target_name: Some("public: virtual char const * __cdecl wil::ResultException::what(void) const"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x666F8, slot: 0, byte_offset: 0, target_rva: 0x22430, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x666F8, slot: 1, byte_offset: 8, target_rva: 0x28550, target_id: Some("?what@exception@std@@UEBAPEBDXZ"), target_name: Some("public: virtual char const * __cdecl std::exception::what(void) const"), ambiguous: false, this_adjustment: None },
];

/// Reads a raw function pointer from an object's primary vftable.
///
/// # Safety
/// `object` must point to a live object with a readable primary vftable,
/// and `slot` must be valid for that concrete object. This function does
/// not invent or transmute a callable signature.
pub unsafe fn raw_object_slot(object: *const c_void, slot: usize) -> Option<*const ()> {
if object.is_null() { return None; }
let table = unsafe { *(object.cast::<*const *const ()>()) };
if table.is_null() { return None; }
let target = unsafe { *table.add(slot) };
(!target.is_null()).then_some(target)
}
